export const pattern1 = [
    [
      {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, { condition: 1},
      {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0},
    ],
    [
      {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, { condition: 1},
      {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0},
    ],
    [
      {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, { condition: 1},
      {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0},
    ],
    [
      {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, { condition: 1},
      {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0},
    ],
    [
      {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, { condition: 1},
      {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0},
    ],
    [
      {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, { condition: 1},
      {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0},
    ],
    [
      {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, { condition: 1},
      {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0},
    ],
    [
      {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, { condition: 1},
      {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0},
    ],
    [
      {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, { condition: 1},
      {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0},
    ],
    [
      {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, { condition: 1},
      {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0},
    ],
    [
      {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, { condition: 1},
      {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0},
    ],
    [
      {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, { condition: 1},
      {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0},
    ],
    [
      {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, { condition: 1},
      {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0},
    ],
    [
      {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, { condition: 1},
      {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0},
    ],
    [
      {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, { condition: 1},
      {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0},
    ],
    [
      {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, { condition: 1},
      {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0},
    ],
    [
      {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, { condition: 1},
      {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0},
    ],
    [
      {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, { condition: 1},
      {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0},
    ],
    [
      {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, { condition: 1},
      {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0},
    ],
    [
      {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, { condition: 1},
      {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0},
    ],
    [
      {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, { condition: 1},
      {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0},
    ],
    [
      {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, { condition: 1},
      {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0},
    ],
    [
      {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, { condition: 1},
      {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0},
    ],
    [
      {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, { condition: 1},
      {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0},
    ],
    [
      {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, { condition: 1},
      {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0},
    ],
    [
      {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, { condition: 1},
      {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0},
    ],
    [
      {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, { condition: 1},
      {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0},
    ],
    [
      {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, { condition: 1},
      {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0},
    ],
    [
      {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, { condition: 1},
      {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0},
    ],
    [
      {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, { condition: 1},
      {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0}, {condition: 1}, {condition: 0},
    ],
    
  ];


  export const pattern2 = [
    [
      {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, { condition: 1},
      {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, { condition: 1},
    ],
    [
      {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, { condition: 1},
      {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, { condition: 1},
    ],
    [
      {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, { condition: 1},
      {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, { condition: 1},
    ],
    [
      {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, { condition: 1},
      {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, { condition: 1},
    ],
    [
      {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, { condition: 1},
      {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, { condition: 1},
    ],
    [
      {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, { condition: 1},
      {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, { condition: 1},
    ],
    [
      {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, { condition: 1},
      {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, { condition: 1},
    ],
    [
      {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, { condition: 1},
      {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, { condition: 1},
    ],
    [
      {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, { condition: 1},
      {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, { condition: 1},
    ],
    [
      {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, { condition: 1},
      {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, { condition: 1},
    ],
    [
      {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, { condition: 1},
      {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, { condition: 1},
    ],
    [
      {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, { condition: 1},
      {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, { condition: 1},
    ],
    [
      {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, { condition: 1},
      {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, { condition: 1},
    ],
    [
      {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, { condition: 1},
      {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, { condition: 1},
    ],
    [
      {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, { condition: 1},
      {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, { condition: 1},
    ],
    [
      {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, { condition: 1},
      {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, { condition: 1},
    ],
    [
      {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, { condition: 1},
      {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, { condition: 1},
    ],
    [
      {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, { condition: 1},
      {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, { condition: 1},
    ],
    [
      {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, { condition: 1},
      {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, { condition: 1},
    ],
    [
      {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, { condition: 1},
      {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, { condition: 1},
    ],
    [
      {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, { condition: 1},
      {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, { condition: 1},
    ],
    [
      {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, { condition: 1},
      {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, { condition: 1},
    ],
    [
      {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, { condition: 1},
      {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, { condition: 1},
    ],
    [
      {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, { condition: 1},
      {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, { condition: 1},
    ],
    [
      {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, { condition: 1},
      {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, { condition: 1},
    ],
    [
      {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, { condition: 1},
      {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, { condition: 1},
    ],
    [
      {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, { condition: 1},
      {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, { condition: 1},
    ],
    [
      {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, { condition: 1},
      {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, { condition: 1},
    ],
    [
      {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, { condition: 1},
      {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, { condition: 1},
    ],
    [
      {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, { condition: 1},
      {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, { condition: 1},
    ],
    [
      {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, { condition: 1},
      {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, {condition: 1}, {condition: 1}, {condition: 0}, {condition: 0}, { condition: 1},
    ],
];